### ISSUE TITLE
Lookbehind is unsupported in Safari

### ISSUE THREAD

**Issue by jwlms** [sindresorhus/humanize-string#22]
Hey this is a very useful package — thanks for publishing it! I did notice however that it doesn't seem to work correctly in Safari. At first glance it seems like the issue is being caused by `decamelize` and its use of lookbehind which isn't supported in Safari. Here's the error I am seeing in case this is something you want to address:

<img width="905" alt="Screen Shot 2022-01-07 at 3 17 40 PM" src="https://user-images.githubusercontent.com/955224/148619707-5ccd7008-f671-47e8-8ddd-de5d1f6dfb98.png">

**Comment by paul-bonnel-fr** [comment]
I confirm this issue appears on Safari Version 15.0 (17612.1.29.5)

**Comment by ebakke** [comment]
We encountered this today on Version 15.3 (17612.4.9.1.8).

Still no support from Apple on the lookbehind https://caniuse.com/js-regexp-lookbehind

**Comment by larsenwork** [comment]
Maybe the readme should be updated similarly to how it's here: https://github.com/sindresorhus/decamelize#install

**Comment by evoactivity** [comment]
If you're using yarn you can add

```json
"resolutions": {
  "humanize-string/decamelize": "3.0.0"
}
```

to your package.json

**Comment by felpin** [comment]
It's finally there on Safari 16.4 🎉

![image](https://github.com/sindresorhus/humanize-string/assets/22778265/99d20748-da1f-4b1f-b43a-79593ae60f5e)
