### ISSUE TITLE
Please consider support for CommonJS

### ISSUE THREAD

**Issue by gustawdaniel** [sindresorhus/humanize-string#23]
You can check this article:

https://formidable.com/blog/2022/victory-esm/

> If you are a library author, please consider producing both ESM and CommonJS code in your packages and using package.json:exports to support both runtimes. If you’re already using a transpilation step like Babel or TypeScript, this should just prove to be a minor tweak to your build and publish scripts. If you’re only going to publish one form of code in your libraries, at this point in time, we advise that it be CommonJS — so that your library can continue to support both CommonJS and ESM upstream libraries and applications.

**Comment by sindresorhus** [comment]
I have no plans for CommonJS support: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
