### ISSUE TITLE
Doesn't work in React Native app

### ISSUE THREAD

**Issue by ray-holland-es** [sindresorhus/humanize-string#24]
This doesn't work on React Native apps, it gives you a really cryptic message. It works on android, android simulator, ios simulator, but doesn't work on physical iPhones.

````
Unhandled JS Exception: Invalid regular expression: invalid group specifier name

no stack

**Comment by sindresorhus** [comment]
This is a problem with React Native. You should open an issue on the React Native issue tracker instead.
